apiVersion: v1
kind: Service
metadata:
  name: flask-mlb-mlops-service
spec:
  selector:
    app: mlb-mlops
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlb-mlops
spec:
  selector:
    matchLabels:
      app: mlb-mlops
  replicas: 3
  template:
    metadata:
      labels:
        app: mlb-mlops
    spec:
      containers:
      - name: mlops-cookbook
        image: mlops-cookbook:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080